fof/table/table.php

Because noobs like me copy this sometimes and wonder why things don't work

Alter doc block to correct function

---

fof/model/behavior/filters.php
fof/model/behavior/language.php
fof/model/model.php

Hi Nicholas,
Now that it is implemented in FOF3 can you add it in FOF 2? It is really missing. :)

Implemented blacklistFilter (FOF 2)

---

fof/form/field/tag.php
fof/form/field/title.php

I didn't port the rest because I'm lazy to copy paste again everything. ^^'

Ported gh-442 for title and tag fields

---

fof/Form/Field/Button.php
fof/Form/Field/Images.php

- Button field: Allowing to use $this->value if needed (attribute `use_value`)
- Images field: new field, returning many images.

Custom fields

---

fof/Form/Field/Relation.php
fof/Model/DataModel.php

BTW, I have a notice now
```
Notice: Only variable references should be returned by reference in /Model/DataModel/Relation.php on line 256
```

Relation name is inside itemName not in the key

---

fof/View/DataView/Form.php

gh-463 fix output control render

---

fof/Configuration/Domain/Models.php

Using foreignKey instead of remoteKey

---

fof/Form/Field/Relation.php

Fixed old FOF2 naming

---

fof/Model/Model.php

The behavior w/o is not the best. :)

Use hash in getState

---

fof/Model/DataModel.php

Changed the position of `foreach` block inside the `if`.

Small optimisation

---

fof/view/json.php

Fixes #497 and related to CMS https://github.com/joomla/joomla-cms/pull/7037

Use raw filter - 'var' is not a valid filter

---

fof/Form/Field/Tag.php

Came across this when a setting multiple="false" on a tag field and no options showed. Removing the code as was done in joomla/joomla-cms#5630 Fixed the issue
I also applied the SQL optimisation PR that we applied in the CMS (joomla/joomla-cms#4114 but with the fix for postgres in joomla/joomla-cms#4842)

Clone of PR https://github.com/akeeba/fof/pull/507 to master

---

fof/Form/Field/Tag.php
fof/Model/DataModel.php
fof/Model/DataModel/Behaviour/Tags.php

Rework tags

---

fof/Factory/Scaffolding/FormErector.php
fof/Form/Field/Relation.php
fof/Render/AkeebaStrapper.php

* `$this->getLangKeyPrefix()` already finish with a _
* The relation field was using the wrong model instance
* A small optimization inside the Render

Bugs fix and optimization

---

fof/Form/Field/Color.php
fof/Render/AkeebaStrapper.php
fof/Toolbar/Toolbar.php

This is my fist Pull Request to the project. Only few details let's say. Fixes, small improvements, and little proposal.

Color Field / Toolbar improvements

---

fof/Controller/Controller.php
fof/Controller/DataController.php
fof/View/DataView/Json.php

See https://github.com/akeeba/fof/issues/521

Added appropriate responses on CRUD json save

---

fof/Container/Container.php
fof/Params/Params.php

Taken directly from AkeebaSubs 5.0
Example:
```php
$apiKey = $this->container->params->get('api_key', false);
$this->container->params->set('api_key', '1bcde');
$this->container->params->setParams(array('param1' => '123', 'param2' => '345'));
```

Added Service to the container to easily get the component's params from Configuration

---

fof/Form/Form.php

My IDE says this class isn't used

---

fof/Form/Field/Button.php

A new introduced attribute in Button Field for sending POST task in the
grid.

Form Field Button - ListItemTask

---

fof/Factory/Scaffolding/BaseErector.php
fof/Form/Field/Numeric.php

Added numeric field Type

---

fof/Controller/DataController.php

If a record is locked to a user then the save method should abort and not continue on regardless

If a record is locked it shouldn't be saved

---

fof/Container/Container.php

Fix description

---

Tests/Controller/DataControllerDataprovider.php
Tests/Factory/Magic/ControllerFactoryDataprovider.php

Fix the unit test failures arising from the introduction of the forceRemove method

Fix unit tests

---

fof/Render/AkeebaStrapper.php

There's several more places in the form fields where I guess this should be done - but these are the two instances in the renderer

Access the session through the container

---

fof/Factory/BasicFactory.php
fof/View/ViewTemplateFinder.php

ViewTemplate folder

---

cli/fof/Command/Generate/ViewBase.php
fof/Container/Container.php
fof/Factory/BasicFactory.php
fof/Factory/FactoryInterface.php
fof/Factory/Scaffolding/Controller/Builder.php
fof/Factory/Scaffolding/Controller/ControllerErector.php
fof/Factory/Scaffolding/Controller/ErectorInterface.php
fof/Factory/Scaffolding/Layout/BaseErector.php
fof/Factory/Scaffolding/Layout/BrowseErector.php
fof/Factory/Scaffolding/Layout/Builder.php
fof/Factory/Scaffolding/Layout/ErectorInterface.php
fof/Factory/Scaffolding/Layout/FormErector.php
fof/Factory/Scaffolding/Layout/ItemErector.php
fof/Factory/Scaffolding/Model/Builder.php
fof/Factory/Scaffolding/Model/ErectorInterface.php
fof/Factory/Scaffolding/Model/ModelErector.php
fof/Factory/Scaffolding/View/Builder.php
fof/Factory/Scaffolding/View/ErectorInterface.php
fof/Factory/Scaffolding/View/ViewErector.php
fof/Utils/ModelTypeHints.php

Expand scaffolding

---

fof/Controller/Controller.php
fof/Controller/DataController.php

Added new variable member to hold cache params

---

fof/Render/AkeebaStrapper.php
fof/Toolbar/Toolbar.php

- Added attr to translate the toobar title when we are using fof.xml
- #571, the first row should be 0 not 1.

Allow to translate toolbar title in fof.xml

---

fof/View/DataView/Csv.php

I need to test the modifications I made work before you merge this :P

Make it possible for the CSV to access relations. Fixes #541

---

fof/utils/update/update.php

Do not prompt to update when the update version is the same of the current version

Fix updater

---

fof/Form/Field/Relation.php

https://github.com/akeeba/fof/commit/baf124c19c3581c326209886f56a16c0b4c06c4c#diff-7e1a61c3bccfab9fb254b83aa95b38c1L180
/cry

[RELATION:ID] was removed

---

fof/Model/DataModel/Behaviour/Filters.php
fof/Model/DataModel/Filter/AbstractFilter.php
fof/Model/DataModel/Filter/Date.php
fof/Model/DataModel/Filter/Number.php
fof/Model/DataModel/Filter/Text.php

I just noticed that this commit disappear during the migration FOF2 -> FOF3 : https://github.com/akeeba/fof/commit/a951fa6c157283ad802d08188fa67e153557b94d

Readded range and modulo filter

---

fof/table/table.php

, and test result for false rather than true.  Works around vagaries in J!'s documentation and driver implementations.  Addresses ...
https://issues.joomla.org/tracker/joomla-cms/8525

Use try/catch in table store()

---

fof/controller/controller.php

Reference: add() method 
It has the layout check done correct.

Editing produces a layout not found error

---

cli/fof/Command/Help.php
cli/fof/Command/Language.php
cli/fof/Command/Language/NodeVisitor/NodeVisitor.php
cli/fof/Command/Language/NodeVisitor/PhpNodeVisitor.php
composer.json
composer.lock

@nikosdion this is what i was thinking ;)

Added language strings generator for fof cli see #647

---

.travis.yml

PHP 7.2 has been released, add to testing on Travis
Allowed Failure until the MySQLi issue on Travis is resolved

PHP 7.2 has been released, add to testing

---

fof/Model/DataModel.php

GitHub ignores the code comment meaning it sees lots of red. Yes I have no life ;)

Amend code comment so github is less sad

---

fof/Model/DataModel/Relation/HasMany.php

Fix eager loading with duplicated values

---

fof/Model/DataModel/Relation/HasMany.php

FOF4: Fix eager loading with duplicated values
