fof/form/field/calendar.php

If you want to display the full month it is ```%B``` in the js calendar. However in PHP this has a completely different meaning. So we should transcribe it to the PHP equivalent (F)

Allow showing full month to work

---

fof/utils/installscript/installscript.php

Now, _createAdminMenus has two queries to delete menu items on level 1 and menu items on level 2.
However..... I found out that the problem is being reintroduced in bugfixDBFunctionReturnedNoError ! I am testing with **Joomla! 3.4.0-dev** ... *and installer type is always "install"* !
At extension installer level, a query after bugfixDBFunctionReturnedNoError solves the issue.

bugfixDBFunctionReturnedNoError and _createAdminMenus

---

fof/Inflector/Inflector.php

Added checks to avoid double pluralization/singularization by the FOF Inflector class. 
This resolves a problem for non-English/custom singular/plural words added with `Inflector::addWord()`.
See also this list message: https://groups.google.com/forum/#!topic/frameworkonframework/FrUPyXML5_Y

Added checks to avoid double singularization and pluralization

---

fof/Form/Form.php

L.637 `$this->container->getNamespacePrefix()` return a namespace finishing by a backslash.
L.656 It result but having a doubleslash in the namespace (E.g Name\Admin\\Form\..)

Fixed namespace with doubleslash

---

fof/form/field/model.php

When you use an empty placeholder for the model form field, the value of its option tag should be empty, and not the same value of the text.

The value of the placeholder should be null and not the same as the text

---

fof/Form/Header/Ordering.php

- !$sortable return is in the top (small optimisation)
- Added attributes for icon and class (Using the previous as default)
- Removed $hasAjaxOrderingSupport
$hasAjaxOrderingSupport is only checking if `ordering` field exists now, and I guess it you are using this Header it mean you have `ordering` field. :)

Removed J!2.5 and added attributes

---

fof/Render/AkeebaStrapper.php
fof/Render/Joomla3.php

`span12` doen't work correctly with the message. Switched to `row-fluid` instead.

Fixed floating sidebar and messages

---

fof/form/field/tag.php

Came across this when a setting ```multiple="false"``` on a tag field and no options showed. Removing the code as was done in https://github.com/joomla/joomla-cms/pull/5630 Fixed the issue
I also applied the SQL optimisation PR that we applied in the CMS (https://github.com/joomla/joomla-cms/pull/4114 but with the fix for postgres in https://github.com/joomla/joomla-cms/pull/4842)

Apply CMS PR #5630

---

fof/utils/installscript/installscript.php

Hi,
uninstallPostInstallationMessages is deleting from array $this->postInstallationMessages, instead of naming the table '#__postinstall_messages'.
To avoid the notice, I have replaced the array with the table.

Array to string conversion in uninstallPostInstallationMessages

---

fof/Controller/DataController.php

Previously it was not possible to create new records through the apis.
Btw, i found new issues related to this:
1) When there is an error in saving, the error is not propagated as an HTTP error but instead it uses the joomla way of enqueueMessage and redirect, which is not how it should work in the REST world
2) When the saving goes well, the system redirects to the read / edit view but skips the format part, so instead of showing the record in json, it prints out the html version of the page.
I can fix these, but i would need some pointing on how: throw / catch and intercept when json, create a onAfterSave / something on the json view class...? 
You call @nikosdion :)

Fixed creation with json apis

---

fof/Render/AkeebaStrapper.php

Small fix. When the sidebar is not used in front, the sidebar container
(span2) should not be outputed.

Akeeba Strapper : Fix sidebar

---

fof/Model/DataModel/Relation/HasMany.php

If you add a second parameter to quote name it will be used as the AS clause https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver.php#L1504

Use the AS parameter in the JDatabase API

---

fof/Layout/LayoutFile.php

Currently when you do something like
```php
echo \FOF30\Layout\LayoutHelper::render($this->getContainer(), 'joomla.form.renderfield', array('input' => '<input type="text" name="variable" value="' . $this->getModel()->variable . '" />', 'label' => '<label>Label For some variable</label>', 'options' => array()));
```
You get nothing back. This is because we are looking in `JOOMLA_ROOT/joomla/form/renderfield.php` instead of `JOOMLA_ROOT/layouts/joomla/form/renderfield.php`

We aren't checking in the layouts directory

---

fof/Toolbar/Toolbar.php

This applies very similar code to that as done for the checkin button in the same method. If there is no `enabled` field present then there's no point in showing the published buttons.
I don't think this could fall under b/c because the `DataModel::published()` bails super early if there is no `enabled` field present

Only show published buttons if a enabled field is present

---

fof/Controller/DataController.php

When saving data has prerequisites (e.g. creating a user) this can be done in the `onBeforeApplySave` method. However is there is an error during the save operation then sometimes the operations need to be 'undone' but currently no method is triggered (if there is an exception thrown in save then the `onAfterApplySave` method is never triggered - and even if it was you wouldn't be able to tell if it was successful or not with the current parameters anyhow.
If gh-547 is merged then this will need to be updated

Add event when saving fails

---

fof/View/DataView/Csv.php

Haven't had time to debug why empty isn't working - I just got as far as debugging that it wasn't but this did work

empty() returns false even when there are no items in a collection

---

fof/View/DataView/Csv.php

When no CSV File name is specified and the default one is used you just have a file downloaded of the format 
`myView` rather than `myView.csv`

Generate CSV file with CSV extension type

---

fof/form/form.php

This might be makes no sense at all because it is 2.x version of fof but this is not the first time that try to remove a header field from a browse form and failed.
So I copied the removeField function from JForm and changed so that it ow removes headers.

adding a remove header function

---

fof/Model/DataModel/Relation/BelongsToMany.php

Allows to save the relation's "links" without saving the object themselves
Normal way of saving items + relations
```php
<?php
// The related Ids to attach
$ids = array(1, 2, 3);
$this->find(1);
$roles = $user->getContainer()->factory->model('Roles')->tmpInstance();
$newRoles = $roles->where(
$roles->getIdFieldName(), 'in', $ids
)->get();
foreach($newRoles as $newRole) {
$this->roles->add($newRole);
}
$this->getRelations()->save('roles');
```
This saves the related items themselves before saving the links, which is not always required and kind of heavy in most cases
With this new method you can also do
```php
<?php
// The related Ids to attach
$ids = array(1, 2, 3);
$this->find(1);
$roles = $user->getContainer()->factory->model('Roles')->tmpInstance();
$newRoles = $roles->where( …
```

Added new saveRelations() method to belongsToMany

---

fof/Form/Field/Calendar.php

After updating FOF3, a client got a small BC break on the Calendar.
On browse view the original behaviour for `empty` dates was to not show them. But now the behaviour is to show the today date.
Well, the change was make 1 year ago... so I'm not sure which one using.
So I made a compromise and added `empty_replacement` param. If the param is not set the current behaviour will apply. Else it will show the `empty_replacement`.

Reallowed empty value for Calendar field

---

fof/database/installer.php

Commit 259256822d1772b88b234a055fca55d8ebb5dc97 changed the way we are fetching the column list, from an array of objects to an array of strings.
I suspect that was a copy/paste error, this PR reverts to the old behavior (array of objects)

Fix database check on column type

---

fof/Form/Field/Relation.php

Relation Form Field now takes into account he parameter [relationclass] even in edit views, for cases when the field name is not the same of the model class name (ie: company_types vs CompanyTypes)

Relation Form Field [relationclass] attribute

---

fof/View/DataView/Csv.php

It can happen that the first model in the csv list to export has some null fields.
If this happens, those fields do not get exported even if some record afterwards has it because isset() checks for null value.
Adding property_exists avoids that case

Export also null fields in CSV

---

.travis.yml
Tests/bootstrap.php
Tests/environments.php

- add PHP 7.1 to tests
- fix HHVM to run on current (3.15.x as of this PR ) rather than the HHVM 3.6.6 version Travis CI precise container is permanently stuck on.
- switch to git clone the joomla branches to test against since the git submodules do not stay current with joomla automatically, the git submodules are left for local testing.

Test against HHVM current and PHP 7.1

---

.travis.yml

Everyone seems to be walking away from HHVM support. Joomla has also removed it from testing.

Remove HHVM

---

fof/Model/DataModel.php

I had issues with the TreeModel. The first find() worked fine, the next one failed. A simplified quote of my code:
foreach ($ids as $id)
{
$this->treeModel->find($id);
}
`whereClauses` was not reset which caused this issue. This PR fixed it.

Fix reset whereClauses

---

Tests/README.md
Tests/Stubs/Utils/IpStub.php
Tests/Utils/IpDataprovider.php
Tests/Utils/IpTest.php
fof/Utils/Ip.php

If the remote site uses a proxy server, the detected IP was wrong: the last IP in the chain was returned and not the first one, as defined by the specs https://en.wikipedia.org/wiki/X-Forwarded-For#Format
This PR fixes this

Fixed IP detection

---

composer.json

Note: This patch only fixes the Build errors, builds might still fail for other reasons (like some issue with mySQLi connection on travis).
`vfsStream` has set their `dev-master` to >PHP 7.1 so we need to Fall back to release `1.6.5` to remove build errors
Reference https://github.com/mikey179/vfsStream/issues/143
Note: they will be changing the package name at some point with the 2.x release
https://github.com/mikey179/vfsStream/issues/144

Fix tests due to vfsStream requirements

---

fof/Utils/InstallScript/Component.php

The function `get` is effectively deprecated as part of the documented change that `JInstallerAdapter` will no longer extend from JAdapterInstance (which has been the case since 3.4 - https://github.com/joomla/joomla-cms/blob/3.7.4/libraries/cms/installer/adapter.php#L21)
`JInstallerAdapter::getManifest` has been the replacement method since 3.4 - so as `InstallScript/Component.php` is supposed to support 3.3 and higher I've added a method exists check.
Also required for Joomla 4.0 compatibility where `JInstallerAdapter::get` has been removed

Get the manifest by it's method in Joomla 3.4+

---

.travis.yml

Travis is throwing a `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)` issue, this is fixed by forcing services to start mysql
also add php 7.3 since it's released

Add services to fix travis error

---

fof/Utils/Ip.php

This PR moves the list of HTTP headers inside a class variable that could be exposed to the other objects.  
In this way other extensions can fetch the list of headers used to get the real IP.  
This PR is full B/C

Refactored IP class to expose HTTP headers involved in proxies

---

fof/Cli/Application.php
fof/Cli/Joomla3.php
fof/Cli/Traits/MessageAware.php

Several core extensions are relying on current Application to be able to handle system messages using the `enqueueMessage` and `getMessageQueue` methods.  
Sadly those methods are a _de facto_ requirement, but they are not declared in low level classes, so any other class extending the core ones `BaseApplication` or `CliApplication` will crash into a fatal error.  
This PR creates a new trait to make your CLI application aware of system messages; code is loosely based on Joomla one.  
This PR is fully B/C

CLI application will handle app messages, too
